### ISSUE TITLE
Applicability

### ISSUE THREAD

**Issue by anilsathyan7** [hessamb/label-refinery#5]
Hi, 
     The results of the paper looks impressive; however can we apply these techniques  
in case of smaller data-sets with few classes and in cases where there is no overlap in labels in the pictures of the dataset ? 
Also  XNOR based implementations of the  models seems to be missing in the repo ...

**Comment by syorami** [comment]
If there is no label overlap in the pictures, this label refinery method could not help. In my CIFAR10 experiments, iterative label refinery produces worse results than baseline. The application scenarios are  limited. @anilsathyan

**Comment by hessamb** [comment]
Hi @anilsathyan7,
Hard to say. The amount of improvement definitely does depend on the dataset. As @tmac1997 mentioned, the accuracy might drop if the generalizability that we get through this approach is "less than" the label noise that we get. I have not done CIFAR10 experiments though.
