### ISSUE TITLE
Question about how label refinery improves the labels

### ISSUE THREAD

**Issue by anjandeepsahni** [hessamb/label-refinery#6]
Hi,

I was reviewing the paper and found the approach to be excellent. Kudos! The results provided in the paper show considerable improvement as well!

My question is in continuation with Issue #2 - I was having some difficulty comprehending the math behind how using soft-labels actually helps improve the network to predict better.

> If the best the "student" can achieve is to produce the same output distribution as the "teacher" does, how is it possible to beat the "teacher"?

Essentially if the output from the first network is [0.1, 0.9] and we are minimizing the loss of the second network to match this distribution, then the gradient will be 0 when the output of the second network is [0.1, 0.9]. If the second network is only going to predict as good as the first network, how does it improve the model?

And why train a second network to produce an output  [0.1, 0.9] when we already have the first network that produces the same output?

Thanks.

**Comment by hessamb** [comment]
Hi @anjandeepsahni,
You are right. This is a mathematical mystery for me as well. It is true that the global optimal for the model to be trained is to become a clone of the refinery network. And that's definitely possible at least in the self-refinery experiments. But it doesn't become a clone according to the experiments, but it becomes a better version of the refinery network. I don't have a good explanation other the obvious "Oh it's non-convex and we're doing stochastic optimization, so it may not get there".

I think this would be a well scoped, and interesting area to study mathematically.
